### dubbo config ###
dubbo:
  application:
    id: ${spring.application.name}-service
    name: ${spring.application.name}-service
  registry:
    id: ${spring.application.name}-registry
    address: zookeeper://192.168.17.128:2181
  protocol:
    id: dubbo
    name: dubbo
    port: -1
    status: server
  metadata-report:
    address: zookeeper://192.168.17.128:2181
  scan:
    base-packages: lon.test.provider.services
  provider:
    timeout: 300000
  consumer:
    timeout: 300000
### dubbo config ###

#log path config
logging:
  path: d:\\data\\applogs\\${spring.application.name}
  level:
    root: debug
#log path config